version: '3'
services:
    wp:
        build: .docker
        volumes:
            - ./.docker/conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./wordpress:/var/www/app
            - .docker/volumes/mu-plugins/mailhog.php:/var/www/app/web/app/mu-plugins/mailhog.php
            - .docker/volumes/wp-graphql:/var/www/app/web/app/plugins/wp-graphql
        ports:
            - "8000:80"
        depends_on:
            - db
        user: www-data
        dns:
            - 8.8.8.8
            - 208.67.222.222
            - 1.1.1.1
    db:
        image: mysql:5
        ports:
            - "3307:3306"
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            MYSQL_DATABASE: 'wordpress'
    mailhog:
        image: mailhog/mailhog
        ports:
            - "1025:1025"
            - "8025:8025"   
    next:
        build: .docker/next
        volumes:
            - ./cms-wordpress-app:/usr/src/app
        command: sh -c "npm install && npm run dev"
        user: node
        environment: 
            - LOCAL_DOMAIN=wp/
        depends_on:
            - wp
        ports:
            - "3000:3000"